Repository chingu-voyages/v22-bears-team-05, pull requests merged in 2020-08, with the labels that each got.

#2 Register Page Form Functionality
  client/.eslintrc.json
  client/components/Forms/Login.tsx
  client/components/Forms/Register.tsx
  client/components/Links.tsx
  client/pages/register.tsx
  client/utils/auth/index.js
  client/utils/auth/login.ts
  client/utils/auth/register.ts
  client/utils/callAPI.ts
  client/utils/graphql/mutation/index.js
  client/utils/graphql/mutation/register.ts
  client/utils/graphql/query/index.js
  client/utils/graphql/query/login.ts
  client/utils/graphql/variables/index.js
  client/utils/graphql/variables/login.ts
  client/utils/graphql/variables/register.ts
  server/graphql/resolvers/users.js
  server/utils/validateRegisterInput.js
Labels: enhancement, needs-review

#3 Update: NavBar changes and more progress toward private auth'd routes
  client/components/App.js
  client/components/Forms/Login.tsx
  client/components/Forms/Register.tsx
  client/components/Links.tsx
  client/components/NavBar.tsx
  client/utils/graphql/documents/auth.ts
  client/utils/graphql/documents/index.js
  client/utils/graphql/mutation/index.js
  client/utils/graphql/mutation/login.ts
  client/utils/graphql/query/index.js
  client/utils/graphql/query/me.ts
  server/graphql/resolvers/users.js
  server/graphql/typeDefs.js
Labels: enhancement, needs-review

#7 Register Checkmark Size Fix
  client/components/Forms/Register.tsx
Labels: enhancement

#5 Start of Integration Testing
  server/.gitignore
  server/graphql/resolvers/users.js
  server/package-lock.json
  server/package.json
  server/testServer.js
  server/tests/app.test.js
  server/tests/dbHandler.js
Labels: needs-review
